# Generated by Django 3.1.6 on 2021-02-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_id', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('prj_title', models.CharField(max_length=100)),
                ('prj_domain', models.CharField(choices=[('CF', 'Corporate Functions'), ('CRM', 'CRM & Billing'), ('CE', 'Customer Engagement'), ('DSS', 'Data Services & Solutions'), ('IS', 'Infrastructure Services'), ('PPRM', 'Program & Product Release Management')], max_length=4)),
                ('prj_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3)),
            ],
        ),
    ]
