# Generated by Django 3.1.6 on 2021-02-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210209_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prj_createdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_estimation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_planned_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_state',
            field=models.CharField(choices=[('1', 'In Idea Phase'), ('2', 'In High Level Scoping'), ('3', 'In Planning'), ('4', 'In Delivery'), ('5', 'Completed')], default='tbd', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_domain',
            field=models.CharField(choices=[('CF', 'Corporate Functions'), ('CRM', 'CRM & Billing'), ('CE', 'Customer Engagement'), ('DSS', 'Data Services & Solutions'), ('IS', 'Infrastructure Services'), ('PPRM', 'Program & Product Release Management')], default='tbd', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='tbd', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_title',
            field=models.CharField(default='tbd', max_length=100),
        ),
    ]
