# Generated by Django 3.1.6 on 2021-02-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210209_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='prj_createdate',
        ),
    ]
