# Generated by Django 3.1.6 on 2021-02-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_project_prj_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='prj_planned_delivery',
        ),
    ]
