# Generated by Django 3.1.6 on 2021-03-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_prj_planned_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('dom_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dom_name', models.CharField(max_length=100)),
                ('dom_domain_lead', models.CharField(max_length=100)),
                ('dom_createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
