# Generated by Django 3.1.6 on 2021-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='dom_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
