# Generated by Django 3.1.6 on 2021-03-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_domains_dom_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStates',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_order', models.IntegerField(unique=True)),
                ('state_createdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TshirtSizes',
            fields=[
                ('tshirt_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tshirt_name', models.CharField(max_length=3)),
                ('tshirt_lower_limit', models.IntegerField()),
                ('tshirt_upper_limit', models.IntegerField()),
                ('tshirt_planning_budget', models.IntegerField()),
                ('tshirt_createdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.domains'),
        ),
    ]
