# Generated by Django 3.1.6 on 2021-03-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210302_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tshirtsizes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.processstates'),
        ),
    ]
