# Generated by Django 3.1.6 on 2021-03-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210302_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('prj_title', models.CharField(default='tbd', max_length=100)),
                ('prj_domain', models.CharField(choices=[('CF', 'Corporate Functions'), ('CRM', 'CRM & Billing'), ('CE', 'Customer Engagement'), ('DSS', 'Data Services & Solutions'), ('IS', 'Infrastructure Services'), ('PPRM', 'Program & Product Release Management')], default='tbd', max_length=4)),
                ('prj_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='tbd', max_length=3)),
                ('prj_state', models.CharField(choices=[('1', 'In Idea Phase'), ('2', 'In High Level Scoping'), ('3', 'In Planning'), ('4', 'In Delivery'), ('5', 'Completed')], default='tbd', max_length=1)),
                ('prj_estimation', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
