# Generated by Django 3.1.6 on 2021-03-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210302_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('prj_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('prj_title', models.CharField(default='tbd', max_length=100)),
                ('prj_estimation', models.FloatField(null=True)),
                ('prj_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domains')),
                ('prj_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tshirtsizes')),
                ('prj_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processstates')),
            ],
        ),
    ]
