# Generated by Django 3.1.6 on 2021-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_domain',
            field=models.CharField(choices=[('CF', 'Corporate Functions'), ('CRM', 'CRM & Billing'), ('CE', 'Customer Engagement'), ('DSS', 'Data Services & Solutions'), ('IS', 'Infrastructure Services'), ('PPRM', 'Program & Product Release Management')], default='CF', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='XS', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_state',
            field=models.CharField(choices=[('1', 'In Idea Phase'), ('2', 'In High Level Scoping'), ('3', 'In Planning'), ('4', 'In Delivery'), ('5', 'Completed')], default='1', max_length=1),
        ),
    ]
