# Generated by Django 3.1.6 on 2021-03-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210302_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domains'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tshirtsizes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processstates'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
