# Generated by Django 3.1.6 on 2021-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210302_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='dom_createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
    ]
