# Generated by Django 3.1.6 on 2021-03-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210302_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='dom_createdate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='dom_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Time'),
        ),
    ]
