# Generated by Django 3.1.6 on 2021-03-02 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210302_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstates',
            name='state_createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processstates',
            name='state_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='prj_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tshirtsizes',
            name='tshirt_createdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tshirtsizes',
            name='tshirt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
