# Generated by Django 3.1.6 on 2021-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210302_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtsizes',
            name='tshirt_createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
