# Generated by Django 3.1.6 on 2021-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210302_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstates',
            name='state_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Date'),
        ),
    ]
