# Generated by Django 3.1.6 on 2021-03-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210302_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstates',
            name='state_createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processstates',
            name='state_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
